---
##
#
# db_name: The name of the database to create.
# db_user: The username of the db user.
# db_pass: The password of the db user.
#
- hosts: all
  become: yes

  vars_prompt:
    - name: db_name
      prompt: "Name of database to create?"
      private: no
    - name: db_user
      prompt: "Name of user to create?"
      private: no
    - name: db_pass
      prompt: "Pass of user?"
      private: yes

  tasks:

    - name: Create MySQL db
      action: mysql_db name={{ db_name }}

    - name: Create MySQL user
      action: mysql_user name={{ db_user }} password={{ db_pass }} priv={{ db_name }}.*:ALL/*.*:SELECT
