---
###
# Vim Customization
#

- name: Vim Customization | Clone repository
  action: git repo=https://github.com/kporras07/.vim.git dest=/home/vagrant/.vim accept_hostkey=yes recursive=yes

- name: Vimrc | Create symlink in /home/vagrant/.vimrc
  action: file src=/home/vagrant/.vim/vimrc dest=/home/vagrant/.vimrc state=link

- name: CodeSniffer | Composer global require
  action: shell composer global require drupal/coder:\>7

- name: CodeSniffer | Install PHP_Codesniffer
  action: shell pear install PHP_CodeSniffer creates=/usr/share/php/PHP/CodeSniffer/

- name: CodeSniffer | Download drupalcs module
  action: get_url url=http://ftp.drupal.org/files/projects/coder-7.x-2.2.tar.gz dest=/home/vagrant/coder-7.x-2.2.tar.gz
- name: CodeSniffer | Extract drupalcs module
  action: shell chdir=/home/vagrant tar xzf coder-7.x-2.2.tar.gz creates=/home/vagrant/coder

- name: CodeSniffer | CS copy standard
  action: shell cp -r /home/vagrant/coder/coder_sniffer/Drupal/ /usr/share/php/PHP/CodeSniffer/Standards/

- name: CodeSniffer | Cleanup
  file: path={{ item }} state=absent
  with_items:
    - /home/vagrant/coder-7.x-2.2.tar.gz
