---
####
# Imagemagick
#
- name: Imagemagick | Install delegates
  action: apt pkg={{ item }} state=installed
  with_items:
    - "libpng-dev"
    - "libjpeg-dev"
    - "libfreetype6-dev"

- name: Imagemagick | Copy source
  action: copy src=tmp/ImageMagick.tar.gz dest=/tmp/ImageMagick.tar.gz

- name: Imagemagick | Untar source
  action: unarchive src=/tmp/ImageMagick.tar.gz dest=/tmp/

- name: Imagemagick | Build and Install
  shell: chdir=/tmp/ImageMagick-6.9.2-4 creates=/usr/local/bin/convert ./configure '--with-png=yes' '--with-jpeg=yes' '--with-jp2=yes' '--with-freetype=yes' && make && make install

- name: Imagemagick | Reload libraries
  shell: ldconfig /usr/local/lib

- name: Imagemagick | Cleanup
  file: path={{ item }} state=absent
  with_items:
    - /tmp/ImageMagick.tar.gz
    - /tmp/ImageMagick-6.9.2-4
