---
- src: geerlingguy.git
  version: 1.2.1
- src: geerlingguy.apache
  version: 2.0.0
- src: geerlingguy.apache-php-fpm
  version: 1.0.2
- src: geerlingguy.nginx
  version: 1.9.6
- src: geerlingguy.mysql
  version: 2.5.0
- src: geerlingguy.php
  version: 3.4.2
- src: geerlingguy.php-pecl
  version: 1.3.0
- src: geerlingguy.php-mysql
  version: 2.0.1
- src: geerlingguy.composer
  version: 1.5.0
- src: geerlingguy.drush
  version: 1.2.0
- src: geerlingguy.php-xdebug
  version: 2.2.0
- src: geerlingguy.blackfire
  version: 1.0.0
- src: geerlingguy.varnish
  version: 1.8.1
- src: geerlingguy.java
  version: 1.7.2
- src: geerlingguy.solr
  version: 3.5.3 
